- name: Set zabbix version for Debian Wheezy
  ansible.builtin.set_fact:
    zabbix_version: "3.0"
  when: ansible_distribution_major_version | int == 7

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: apt

- name: Install apt repo for zabbix {{ zabbix_version }}
  ansible.builtin.apt:
    deb: "http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+{{ ansible_distribution_release }}_all.deb"
  when:
    - zabbix_version_major | int < 6
    - "'zabbix-release' not in ansible_facts.packages"

- name: Install apt repo for zabbix {{ zabbix_version }}
  ansible.builtin.apt:
    deb: "http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/pool/main/z/zabbix-release/zabbix-release_latest+debian{{ ansible_distribution_major_version }}_all.deb"
  when:
    - zabbix_version_major | int == 6
    - "'zabbix-release' not in ansible_facts.packages"

- name: Install zabbix_get
  ansible.builtin.apt:
    pkg: zabbix-get
    autoclean: true
    update_cache: true
  when:
    - zabbix_version_major | int <= 7
  
- name: Set zabbix_agent_version for Debian Wheezy or Jessie
  ansible.builtin.set_fact:
    zabbix_agent_version: "1"
  when: ansible_distribution_major_version | int <= 8

- name: Zabbix_agentd (legacy)
  ansible.builtin.include_tasks: debian_zabbix_agentd.yml
  when: zabbix_agent_version | int == 1

- name: Zabbix_agent2 (current)
  ansible.builtin.include_tasks: debian_zabbix_agent2.yml
  when: zabbix_agent_version | int == 2

- name: Add user zabbix to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "zabbix ALL=(ALL) NOPASSWD:/usr/sbin/smartctl"
    validate: /usr/sbin/visudo -cf %s
  when: ansible_virtualization_tech_guest | length == 0
