- name: Set zabbix version
  ansible.builtin.set_fact:
    zabbix_version: "{{ zabbix_version_major }}.{{ zabbix_version_minor }}"

- name: Show zabbix version
  ansible.builtin.debug:
    msg: "zabbix_version: {{ zabbix_version }}"

- name: Setup zabbix-agent
  ansible.builtin.include_tasks: setup.yml
  when: zabbix_server is defined

- name: Register zabbix-agent
  ansible.builtin.include_tasks: register.yml
  when: zabbix_server is defined
