- name: Set zabbix version
  ansible.builtin.set_fact:
    zabbix_version: "{{ zabbix_version_major }}.{{ zabbix_version_minor }}"

- name: Show zabbix version
  ansible.builtin.debug:
    msg: "zabbix_version: {{ zabbix_version }}"

- name: Create /etc/zabbix/
  ansible.builtin.file:
    path: /etc/zabbix/
    owner: root
    group: root
    state: directory
    mode: "0755"

- name: Debian
  ansible.builtin.import_tasks: debian.yml
  when:
    - ansible_distribution == 'Debian'

- name: Xenserver
  ansible.builtin.import_tasks: xenserver.yml
  when:
    - ansible_distribution == 'XenServer'
    - ansible_distribution_major_version | int == 7

- name: Register zabbix-agent
  delegate_to: "{{ zabbix_server }}"
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_user: "{{ zabbix_user }}"
    ansible_httpapi_pass: "{{ zabbix_api_password }}"
    ansible_zabbix_url_path: ""
  community.zabbix.zabbix_host:
    host_name: "{{ inventory_hostname }}"
    host_groups: "{{ zabbix_group }}"
    link_templates: "{{ zabbix_templates }}"
    interfaces:
      - ip: "{{ zabbix_listen_ip }}"
        type: 1
        useip: 1
        main: 1
    tls_psk_identity: "{{ inventory_hostname }}"
    tls_accept: 2
    tls_connect: 2
    tls_psk: "{{ zabbix_password }}"
  when: zabbix_server is defined
  tags: qa
