- name: install apt repo for zabbix 5.0
  apt:
    deb: "http://repo.zabbix.com/zabbix/5.0/debian/pool/main/z/zabbix-release/zabbix-release_5.0-1+{{ ansible_distribution_release }}_all.deb"
  register: zbx_install_apt_repo

- name: apt update
  apt:
    update_cache: yes
  when: zbx_install_apt_repo is changed

- name: set zabbix_agent_version for Debian Jessie
  set_fact:
    zabbix_agent_version: 1
  when: ansible_distribution_release == 'jessie'

- name: create /etc/zabbix/
  file:
    path: /etc/zabbix/
    owner: root
    group: root
    state: directory
    mode: 0755

- name: zabbix_agentd (legacy)
  include: zabbix_agentd.yml
  when: zabbix_agent_version == 1

- name: zabbix_agent2 (current)
  include: zabbix_agent2.yml
  when: zabbix_agent_version == 2

- name: register zabbix-agent
  local_action:
    module: zabbix_host
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_user|default('ansible') }}"
    login_password: "{{ zabbix_api_password }}"
    host_name: "{{ inventory_hostname }}"
    host_groups: "{{ zabbix_group }}"
    link_templates: "{{ zabbix_templates }}"
    interfaces:
      - ip: "{{ zabbix_listen_ip }}"
        type: 1
        useip: 1
        main: 1
    tls_psk_identity: "{{ inventory_hostname }}"
    tls_connect: 2
    tls_psk: "{{ zabbix_password }}"
  when: zabbix_password is defined
  no_log: true

- name: register zabbix-agent
  local_action:
    module: zabbix_host
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_user|default('ansible') }}"
    login_password: "{{ zabbix_api_password }}"
    host_name: "{{ inventory_hostname }}"
    host_groups: "{{ zabbix_group }}"
    link_templates: "{{ zabbix_templates }}"
    interfaces:
      - ip: "{{ zabbix_listen_ip }}"
        type: 1
        useip: 1
        main: 1
  when: not zabbix_password is defined
  no_log: true
