- name:                   set zabbix version
  set_fact:
    zabbix_version:       "{{ zabbix_version_major }}.{{ zabbix_version_minor }}"

- name: create /etc/zabbix/
  file:
    path: /etc/zabbix/
    owner: root
    group: root
    state: directory
    mode: 0755

- name: debian
  import_tasks: debian.yml
  when:
    - ansible_distribution == 'Debian'

- name: xenserver
  import_tasks: xenserver.yml
  when:
    - ansible_distribution == 'XenServer'
    - ansible_distribution_major_version | int == 7

- name: register zabbix-agent
  local_action:
    module: zabbix_host
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_user|default('ansible') }}"
    login_password: "{{ zabbix_api_password }}"
    host_name: "{{ inventory_hostname }}"
    host_groups: "{{ zabbix_group }}"
    link_templates: "{{ zabbix_templates }}"
    interfaces:
      - ip: "{{ zabbix_listen_ip }}"
        type: 1
        useip: 1
        main: 1
    tls_psk_identity: "{{ inventory_hostname }}"
    tls_accept: 2
    tls_connect: 2
    tls_psk: "{{ zabbix_password }}"
  when: zabbix_url is defined
