- name: set zabbix version for Debian Wheezy
  set_fact:
    zabbix_version: 3.0
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version | int == 7

- name: install apt repo for zabbix {{ zabbix_version }}
  apt:
    deb: "http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+{{ ansible_distribution_release }}_all.deb"
  register: zbx_install_apt_repo
  when:
    - ansible_distribution == 'Debian'

- name: apt update
  apt:
    update_cache: yes
  when:
    - zbx_install_apt_repo is changed
    - ansible_distribution == 'Debian'

- name: set zabbix_agent_version for Debian Wheezy or Jessie
  set_fact:
    zabbix_agent_version: 1
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version | int <= 8

- name: create /etc/zabbix/
  file:
    path: /etc/zabbix/
    owner: root
    group: root
    state: directory
    mode: 0755

- name: zabbix_agentd (legacy)
  include_tasks: zabbix_agentd.yml
  when: zabbix_agent_version == 1

- name: zabbix_agent2 (current)
  include_tasks: zabbix_agent2.yml
  when: zabbix_agent_version == 2

- name: register zabbix-agent
  include_tasks: zabbix_register.yml
  when: zabbix_url is defined
