- name: Debug
  ansible.builtin.debug:
  msg: |
    ansible_httpapi_port: "{{ zabbix_api_port }}"
    ansible_httpapi_use_ssl: "{{ zabbix_api_ssl }}"
    ansible_user: "{{ zabbix_user }}"
    host_name: "{{ inventory_hostname }}"
    zabbix_group: "{{ zabbix_group }}"
    zabbix_templates: "{{ zabbix_templates }}"
    zabbix_listen_ip: "{{ zabbix_listen_ip }}"

- name: Register zabbix-agent
  delegate_to: "{{ zabbix_server }}"
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: "{{ zabbix_api_port }}"
    ansible_httpapi_use_ssl: "{{ zabbix_api_ssl }}"
    ansible_user: "{{ zabbix_user }}"
    ansible_httpapi_pass: "{{ zabbix_api_password }}"
    host_name: "{{ inventory_hostname }}"
    host_groups: "{{ zabbix_group }}"
    link_templates: "{{ zabbix_templates }}"
    interfaces:
    tls_psk: "{{ zabbix_password }}"
