- name: Delete zabbix-agent on Xen
  ansible.builtin.yum:
    name: zabbix-agent
    state: absent

- name: Chech if zabbix_agent2 is installed
  ansible.builtin.stat:
    path: /usr/sbin/zabbix_agent2
  register: zabbix_agent2

- name: Get latest minor version
  delegate_to: localhost
  ansible.builtin.shell: >
    curl --silent http://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/7/x86_64/ |
    grep zabbix-agent2 | cut -d '>' -f 2 | cut -d '<' -f 1 | cut -d . -f 3 | cut -d '-' -f 1 | sort -g | tail -n 1
  register: zabbix_latest_minor_version_curl
  when: not zabbix_agent2.stat.exists
  tags: skip_ansible_lint

- name: Set latest minor version
  ansible.builtin.set_fact:
    zabbix_latest_minor_version: "{{ zabbix_latest_minor_version_curl.stdout }}"
  when: not zabbix_agent2.stat.exists

- name: Debug
  ansible.builtin.debug:
    msg: "{{ zabbix_latest_minor_version }}"
  when: not zabbix_agent2.stat.exists

- name: Install zabbix-agent2 on Xen
  ansible.builtin.yum:
    name:
      - http://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/7/x86_64/zabbix-agent2-{{ zabbix_version }}.{{ zabbix_latest_minor_version }}-1.el7.x86_64.rpm
      - http://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/7/x86_64/zabbix-get-{{ zabbix_version }}.{{ zabbix_latest_minor_version }}-1.el7.x86_64.rpm
    state: present
  when: not zabbix_agent2.stat.exists

- name: Config zabbix-agent2
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/zabbix/{{ item }}"
    owner: zabbix
    group: zabbix
    mode: "0640"
  loop:
    - zabbix_agent2.conf
    - zabbix_agent2.psk
  notify: Restart zabbix_agent

- name: Copy user_parameter
  ansible.builtin.copy:
    src: user_parameter/
    dest: /etc/zabbix/zabbix_agent2.d/
    owner: zabbix
    group: zabbix
    mode: "0640"
  notify: Restart zabbix_agent

- name: Add user zabbix to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "zabbix ALL=(ALL) NOPASSWD:/usr/sbin/smartctl"
    validate: /usr/sbin/visudo -cf %s
