- name: delete zabbix-agent2
  apt:
    pkg: zabbix-agent2
    state: absent
  when: ansible_distribution == 'Debian'

- name: install zabbix-agent
  apt:
    pkg: zabbix-agent
    update_cache: true
    autoclean: true
  when: ansible_distribution == 'Debian'

- name: create /etc/zabbix/zabbix_agentd.d
  file:
    path: /etc/zabbix/zabbix_agentd.d
    owner: zabbix
    group: zabbix
    state: directory
    mode: 0750

- name: config zabbix-agent
  template:
    src: "{{ item }}.j2"
    dest: "/etc/zabbix/{{ item }}"
    owner: zabbix
    group: zabbix
    mode: 0640
  loop:
    - zabbix_agentd.conf
    - zabbix_agentd.psk
  notify: restart zabbix_agent
