- name: delete zabbix-agentd
  apt:
    pkg:
      - zabbix_agent
      - zabbix_agentd
      - zabbix-agent
    state: absent
  when: ansible_distribution == 'Debian'

- name: install zabbix-agent2
  apt:
    pkg: zabbix-agent2
    update_cache: true
    autoclean: true
  when: ansible_distribution == 'Debian'

- name: install zabbix-agent2 on Xen
  yum:
    name: http://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-agent2-5.0.9-1.el7.x86_64.rpm
    state: present
  when:
    - ansible_distribution == 'XenServer'
    - ansible_distribution_major_version | int == 7

- name: config zabbix-agent2
  template:
    src: "{{ item }}.j2"
    dest: "/etc/zabbix/{{ item }}"
    owner: zabbix
    group: zabbix
    mode: 0640
  loop:
    - zabbix_agent2.conf
    - zabbix_agent2.psk
  notify: restart zabbix_agent

- name: copy user_parameter
  copy:
    src: user_parameter/
    dest: /etc/zabbix/zabbix_agent2.d/
    owner: zabbix
    group: zabbix
    mode: 0640
  notify: restart zabbix_agent
