- name: restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes
  listen: restart zabbix_agent
  when: zabbix_agent_version == 1

- name: restart zabbix-agent2
  service:
    name: zabbix-agent2
    state: restarted
    enabled: yes
  listen: restart zabbix_agent
  when: zabbix_agent_version == 2
