- name: Restart zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: true
  listen: Restart zabbix_agent
  when: zabbix_agent_version == 1

- name: Restart zabbix-agent2
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted
    enabled: true
  listen: Restart zabbix_agent
  when: zabbix_agent_version == 2
