- name: Restart zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: true
  listen: Restart zabbix_agent
  when:
    - zabbix_agent_version == 1
    - not ansible_check_mode

- name: Restart zabbix-agent2
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted
    enabled: true
  listen: Restart zabbix_agent
  when:
    - zabbix_agent_version == 2
    - not ansible_check_mode
